### ISSUE TITLE
[all] Enable CI/CD using `run.nu`

### ISSUE THREAD

**Issue by nazmulidris** [r3bl-org/r3bl_rs_utils#154]
Related issue: #120 

### More information about nushell's gh action

From: https://github.com/r3bl-org/r3bl_rs_utils/issues/120#issuecomment-1723232767

>  We use this GitHub Action, created by one of our maintainers, to use nushell in our CI. https://github.com/marketplace/actions/setup-nu.
> 
> Just dropping by to say Hi! 👋🏻 from nushell.

### Using unofficial [`actions-rs`](https://github.com/actions-rs/cargo)

This snippet allows the use of `nu` in Github Actions environment. 

```yml
name: Rust CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Install Nu
      run: cargo install nu
    - name: Build
      run: cargo build
```

- More info: https://dev.to/wayofthepie/rust-and-github-actions-3kob

### Other actions

- https://alican.codes/rust-github-actions
- https://shift.click/blog/github-actions-rust/#quick-setup--overview
- https://dev.to/infinyon/github-actions-best-practices-for-rust-projects-1j9p

## Related

Consider using cargo binstall to speed up builds in ci/cd
- https://github.com/cargo-bins/cargo-binstall

Tracking issue
- https://github.com/r3bl-org/r3bl_rs_utils/issues/122

Related issue
- https://github.com/r3bl-org/r3bl_rs_utils/issues/86

Once the fixes to `r3bl_rs_utils_core` is made (for logging), update `Cargo.toml` & use the
release version of this crate. Then publish to `crates.io`.
